-- 删除所有视图
DROP VIEW IF EXISTS v_milestone_weight_sum CASCADE;
DROP VIEW IF EXISTS v_indicator_latest_report CASCADE;
DROP VIEW IF EXISTS v_overdue_milestones CASCADE;

-- 删除所有表（按依赖顺序）
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS adhoc_task_indicator_map CASCADE;
DROP TABLE IF EXISTS adhoc_task_target CASCADE;
DROP TABLE IF EXISTS alert_event CASCADE;
DROP TABLE IF EXISTS alert_rule CASCADE;
DROP TABLE IF EXISTS alert_window CASCADE;
DROP TABLE IF EXISTS approval_record CASCADE;
DROP TABLE IF EXISTS progress_report CASCADE;
DROP TABLE IF EXISTS milestone CASCADE;
DROP TABLE IF EXISTS indicator CASCADE;
DROP TABLE IF EXISTS adhoc_task CASCADE;
DROP TABLE IF EXISTS strategic_task CASCADE;
DROP TABLE IF EXISTS assessment_cycle CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS org CASCADE;

-- 删除所有枚举类型
DROP TYPE IF EXISTS audit_entity_type CASCADE;
DROP TYPE IF EXISTS audit_action CASCADE;
DROP TYPE IF EXISTS adhoc_task_status CASCADE;
DROP TYPE IF EXISTS adhoc_scope_type CASCADE;
DROP TYPE IF EXISTS alert_status CASCADE;
DROP TYPE IF EXISTS alert_severity CASCADE;
DROP TYPE IF EXISTS approval_action CASCADE;
DROP TYPE IF EXISTS report_status CASCADE;
DROP TYPE IF EXISTS milestone_status CASCADE;
DROP TYPE IF EXISTS indicator_status CASCADE;
DROP TYPE IF EXISTS indicator_level CASCADE;
DROP TYPE IF EXISTS task_type CASCADE;
DROP TYPE IF EXISTS org_type CASCADE;

-- 删除函数
DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;
